### ISSUE TITLE
fireEvent on Text elements

### ISSUE THREAD

**Issue by mcgloneleviROOT** [bcarroll22/native-testing-library#3]
Problem:

I was using this testing framework to test an onPress event on a Text component from React Native.  When I ran this line:

```
fireEvent.press(wrapper.getByText('Open Settings'));
```

I received this error:

No target found for event: "press"

I believe "Text" should be added under eventMap.press.validTargets in https://github.com/bcarroll22/native-testing-library/blob/master/src/events.js

**Comment by mcgloneleviROOT** [comment]
It looks like text elements can be the target of press, longPress, pressIn, pressOut events:

https://github.com/facebook/react-native/blob/master/Libraries/Text/Text.js

**Comment by bcarroll22** [comment]
Fixed in 1.5.1

**Comment by mcgloneleviROOT** [comment]
Thank you!!!
